#!/bin/bash

RCFILE="$HOME/.rundeckclirc"
NAME="rundeck-cli"


# Authenticate and send a request to a API endpoint
request()
{
    [ ! -f ${RCFILE} ] && return 1
    source ${RCFILE}
    [ -n "${RDEndpoint}" -a -n "${RDToken}" ] || return 1

    # Resouce path must start with "/"
    [ -n "${1}" -a "${1:0:1}" == '/' ] || return 70

    curl -v -L ${*:2:${#}} -H "X-Rundeck-Auth-Token: ${RDToken}" "${RDEndpoint}${1}"
    return $?
}


# Print usage
usage()
{
    cat <<EOL
Usage: $0 <COMMAND> [OPTION]

    COMMAND:
        init                        Initialize connecting settings.
        list-jobs <PROJECT>         List jobs for project.
	list-running-jobs <PROJECT> List running jobs for project.
        get-job <ID> [FORMAT]       Export a job <ID>. <FORMAT> is "xml" or "yaml". Default "yaml"
        import-jobs <PATH> <FORMAT> Import <FORMAT> types jobs defined in <PATH>.
EOL
}


# Get a job definition
get-job()
{
    [ -n "$2" ] || return 1
    request "/api/1/job/${2}?format=${3:-yaml}"
    return $?
}


# List jobs for project
list-jobs()
{
    [ -n "$2" ] || return 1
    request "/api/2/project/${2}/jobs" | \
        awk '$1 == "<job" { print $2 }' | \
        sed -e "s|^id='\([^']\+\)'.*$|- \1|"
    return $?
}

# List running jobs for project
list-running-jobs()
{
	[ -n "$2" ] || return 1
    	request "/api/18/project/${2}/executions/running" | grep '\(execution\|<name>\)'
    	return $?
}


# Import jobs
import-jobs()
{
    [ -n "$2" -a -n "$3" ] || return 1
    request "/api/1/jobs/import?format=${3}&dupeOption=update" -X POSt -F xmlBatch=@${2}
    return $?
}


# Initaialize connecting settings
init()
{
    [ -f "${RCFILE}" ] && source ${RCFILE}
    read -p "Endpoint [${RDEndpoint:-None}]: " tmp_rd_endpoint
    read -p "Token [${RDToken:-None}]: " tmp_rd_token

    [ -n "${tmp_rd_endpoint}" ] && RDEndpoint=${tmp_rd_endpoint}
    [ -n "${tmp_rd_token}" ] && RDToken=${tmp_rd_token}

    [ -n "${RDEndpoint}" ] && [ -n "${RDToken}" ] && (
        cat <<EOL > ${RCFILE}
# AUTO GENERATED
RDEndpoint=${RDEndpoint}
RDToken=${RDToken}
EOL
    )
    return 1
}


# Entry point
main()
{
    cmd=""
    case "$1" in
        init|get-job|list-jobs|list-running-jobs|usage|import-jobs)
            ${1} $*
            exit $?;;
        *)
            usage $*
            exit 1;;
    esac
}


# Call entry point when this script is called directly
[ "$(echo -n ${0} | rev | cut -d'/' -f1 | rev)" == "${NAME}" ] && \
    main $* ||\
    true
